export const MESSAGES = {
  LOADING_CONFIG: 'Carregando configuração…',
  SAVING: 'Salvando…',
  SAVE_SUCCESS: 'Configuração salva.',
  ERROR_LOAD: 'Falha ao carregar configuração.',
  ERROR_SAVE: 'Erro ao salvar configuração.',
};

export const CONFIG_DEFAULTS = {
  // === EQUIPES / SAVES (config global — ver PRD sistema de equipes) ===
  teamMemberSlots: 3,
  maxTeamsPerUser: 2,
  saveTrashRetentionDays: 7,
  reviveHpPercent: 0.3,
  initialStatPoints: 6,
  baselinePerStat: 1,
  statPointsPerLevel: 1,
  statPointsLevelInterval: 2,
  maxStatValue: 24,
  minStatValue: 1,
  maxLevel: 99,
  maxStatPointsPerClass: 18,
  enemyInitialStatPoints: 6,
  enemyStatPointsPerLevel: 1,
  enemyTypeMultiplierNormal: 1,
  enemyTypeMultiplierElite: 1.67,
  enemyTypeMultiplierBoss: 3.33,
  minutesPerUnit: 1,
  questQueueSize: 3,
  movementSpeedStatKey: 'dex'
};

export const SETTINGS_SECTIONS = [
  {
    id: 'teams',
    icon: 'FaUsers',
    title: 'Equipes / Saves',
    fields: [
      {
        key: 'teamMemberSlots',
        label: 'Personagens por Equipe',
        type: 'number',
        min: 1,
        helpText: 'Tamanho da formação (hoje = tamanho do roster). Padrão: 3.',
      },
      {
        key: 'maxTeamsPerUser',
        label: 'Máx. de Equipes (saves) por Conta',
        type: 'number',
        min: 1,
        helpText: 'Cada equipe é um slot de save independente. Padrão: 2.',
      },
      {
        key: 'saveTrashRetentionDays',
        label: 'Dias na Lixeira antes do Purge',
        type: 'number',
        min: 1,
        helpText: 'Prazo para restaurar um save apagado antes da remoção definitiva.',
      },
      {
        key: 'reviveHpPercent',
        label: 'HP ao sair do estado Incapacitado (0–1)',
        type: 'number',
        min: 0,
        step: 0.05,
        helpText: 'Fração do HP máximo com que o personagem volta após ser curado.',
      },
    ],
  },
  {
    id: 'stats',
    icon: 'FaDice',
    title: 'Sistema de Atributos (Stats)',
    fields: [
      {
        key: 'initialStatPoints',
        label: 'Pontos Iniciais de Atributos',
        type: 'number',
        min: 0,
        helpText: 'Pontos extras distribuíveis na criação do personagem',
      },
      {
        key: 'maxStatPointsPerClass',
        label: 'Máximo de Pontos por Classe',
        type: 'number',
        min: 1,
        helpText: 'Limite total de pontos que podem ser distribuídos na criação',
      },
      {
        key: 'baselinePerStat',
        label: 'Valor Base por Atributo',
        type: 'number',
        min: 1,
        helpText: 'Valor mínimo inicial de cada atributo',
      },
      {
        key: 'minStatValue',
        label: 'Valor Mínimo de Atributo',
        type: 'number',
        min: 1,
      },
      {
        key: 'maxStatValue',
        label: 'Valor Máximo de Atributo',
        type: 'number',
        min: 1,
      },
    ],
  },
  {
    id: 'progression',
    icon: 'FaGamepad',
    title: 'Progressão e Level-Up',
    fields: [
      {
        key: 'statPointsPerLevel',
        label: 'Pontos por Nível',
        type: 'number',
        min: 0,
        helpText: 'Quantos pontos de atributo o jogador ganha por level-up',
      },
      {
        key: 'statPointsLevelInterval',
        label: 'A Cada Quantos Níveis',
        type: 'number',
        min: 1,
        helpText: 'Intervalo de níveis para ganhar pontos manuais (ex: 2 = níveis 2, 4, 6...)',
      },
      {
        key: 'maxLevel',
        label: 'Nível Máximo de Personagem',
        type: 'number',
        min: 1,
      },
    ],
  },
  {
    id: 'world',
    icon: 'FaMap',
    title: 'Mundo e Gameplay',
    fields: [
      {
        key: 'minutesPerUnit',
        label: 'Tempo de Viagem (min/unidade)',
        type: 'number',
        min: 0.01,
        step: 0.01,
        helpText: 'Minutos necessários para percorrer 1 unidade de distância',
      },
      {
        key: 'questQueueSize',
        label: 'Tamanho da Fila de Quests',
        type: 'number',
        min: 1,
        helpText: 'Número máximo de quests na fila por personagem',
      },
      {
        key: 'movementSpeedStatKey',
        label: 'Stat de Velocidade de Movimento',
        type: 'text',
        helpText: 'Chave do stat usado para calcular velocidade de deslocamento (ex: dex)',
      },
    ],
  },
  {
    id: 'enemies',
    icon: 'FaSkull',
    title: 'Configuração de Inimigos',
    fields: [
      {
        key: 'enemyInitialStatPoints',
        label: 'Pontos Iniciais de Stats (Nível 1)',
        type: 'number',
        min: 0,
        helpText: 'Total de pontos de atributo que um inimigo nível 1 tem para distribuir',
      },
      {
        key: 'enemyStatPointsPerLevel',
        label: 'Pontos Extras por Nível',
        type: 'number',
        min: 0,
        helpText: 'Quantos pontos a mais o inimigo ganha a cada nível acima do 1',
      },
      {
        key: 'enemyTypeMultiplierNormal',
        label: 'Multiplicador: Normal',
        type: 'number',
        min: 0.1,
        step: 0.01,
        helpText: 'Multiplicador de pontos para inimigos do tipo Normal',
      },
      {
        key: 'enemyTypeMultiplierElite',
        label: 'Multiplicador: Elite',
        type: 'number',
        min: 0.1,
        step: 0.01,
        helpText: 'Multiplicador de pontos para inimigos do tipo Elite',
      },
      {
        key: 'enemyTypeMultiplierBoss',
        label: 'Multiplicador: Boss',
        type: 'number',
        min: 0.1,
        step: 0.01,
        helpText: 'Multiplicador de pontos para inimigos do tipo Boss',
      },
    ],
  },
];
